In [1]:
import pandas as pd
import numpy as np

In [7]:
#Wczytanie Danych
url = "https://storage.googleapis.com/download.tensorflow.org/data/heart.csv"
df = pd.read_csv(url)

In [9]:
df.shape

(303, 14)

In [11]:
df.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,1,145,233,1,2,150,0,2.3,3,0,fixed,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,normal,1
2,67,1,4,120,229,0,2,129,1,2.6,2,2,reversible,0
3,37,1,3,130,250,0,0,187,0,3.5,3,0,normal,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,normal,0

In [21]:
#Sprawdzamy proporcje
df["target"].value_counts()

target
0    220
1     83
Name: count, dtype: int64

In [23]:
#Sprawdzamy czy są wystepują NaN
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [27]:
#Tworzymy zamieniamy dane tekstowe na liczbowe
df_new = pd.get_dummies(df, drop_first = True, dtype= int)
df_new.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,target,thal_2,thal_fixed,thal_normal,thal_reversible
0,63,1,1,145,233,1,2,150,0,2.3,3,0,0,0,1,0,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,1,0,0,1,0
2,67,1,4,120,229,0,2,129,1,2.6,2,2,0,0,0,0,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0,0,0,0,1,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,0,0,0,1,0

In [31]:
#Tworzymy dane dla modelu
y = df_new["target"]
X = df_new.drop(["target"], axis = 1)

In [33]:
#Dzielimy zbiór na train/test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=42)

In [39]:
#Skalowanie danych
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [41]:
#Tworzenie modelu 
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model = model.fit(X_train, y_train)

In [45]:
#Tworzenie predykcji
from sklearn.metrics import confusion_matrix, classification_report
y_hat = model.predict(X_test)

#Confusion matrix
print(confusion_matrix(y_test, y_hat))

[[40  4]
 [ 5 12]]

In [47]:
#Classification report
print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

           0       0.89      0.91      0.90        44
           1       0.75      0.71      0.73        17

    accuracy                           0.85        61
   macro avg       0.82      0.81      0.81        61
weighted avg       0.85      0.85      0.85        61

In [51]:
#Dostrajamy model 
y_prob = model.predict_proba(X_test)[:, 1]
prog = 0.3
y_pred_custom = (y_prob >= prog).astype(int)
#Confusion Matrix
print(confusion_matrix(y_test, y_pred_custom))

[[38  6]
 [ 5 12]]

In [53]:
#Clasification report
print(classification_report(y_test, y_pred_custom))

              precision    recall  f1-score   support

           0       0.88      0.86      0.87        44
           1       0.67      0.71      0.69        17

    accuracy                           0.82        61
   macro avg       0.78      0.78      0.78        61
weighted avg       0.82      0.82      0.82        61